# This is a basic workflow to help you get started with Actions

name: Python Runtimes Build and Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ master ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

permissions: read-all

jobs:

  Test:

    runs-on: ubuntu-22.04
      # Checkout just this repo and run scanCode before we do anything else
    steps:
      - name: Checkout runtime repo
        uses: actions/checkout@v3
        with:
          path: runtime

      # Install core OpenWhisk artifacts needed to build/test anything else
      - name: Checkout OpenWhisk core repo
        uses: actions/checkout@v3
        with:
          repository: ibm-functions/openwhisk
          ref: 92f5d870bdecf01ccf0bf46baac582955fdbdfa6
          path: core
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Compile and Install Core OpenWhisk
        working-directory: core
        run: |
          ./gradlew :tests:compileTestScala
          ./gradlew install

      # Build this repository
      - name: Build Runtime
        working-directory: runtime
        run: |
          ./gradlew distDocker
      # Test this repository
      - name: Test Runtime
        working-directory: runtime
        run: |
          ./gradlew :tests:checkScalafmtAll
          ./gradlew :tests:test

